### PR TITLE
fix: support next.config.mjs

### LINKED ISSUE #387: In NativeESM environment, path resolution inside the library fails and does not work properly with nextjs
## Detail

If you set `type: "module"` in Package.json and run it in the NativeESM environment, path resolution will fail and you will not be able to start the nextjs development server. The error message is below.

```sh
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '[path-to-project]/node_modules/next/dist/build/webpack/config/blocks/css' is not supported resolving ES modules imported from [path-to-project]/node_modules/@kuma-ui/next-plugin/dist/index.mjs
Did you mean to import nextjs/node_modules/next/dist/build/webpack/config/blocks/css/index.js?
    at finalizeResolution (node:internal/modules/esm/resolve:249:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///[path-to-project]/node_modules/next/dist/build/webpack/config/blocks/css'
}

Node.js v20.10.0
```

Currently, it is possible to avoid this by setting `type: "commonjs"` and writing next.config.js in commonjs format, but some libraries have appeared that only support native esm. in nextjs config is only support the `.js` extension and the native esm library cannot be used in nextjs unless esm is defined in the package.json definition, it is very inconvenient not to support esm. This will be the reason for not adopting it.

I would be happy if you could support ESM.

## Enviroment

```
❯ yarn next info

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:25 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6020
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 4.0.2
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.28
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: standalone
```

### esm version(It's not running)
- https://github.com/mecaota/bugged-nextjs/tree/feature/kumaui

### commonjs version(it's running)
- https://github.com/mecaota/bugged-nextjs/tree/feature/kumaui-commonjs

### PR DESCRIPTION
**Pull request by taishinaritomi**
Fix #387

### CODE REVIEW

File: packages/webpack-plugin/src/plugin.ts [hunk 1]
```diff
@@ -3,22 +3,20 @@ import { theme } from "@kuma-ui/sheet";
 import path from "path";
 import { readdirSync } from "fs";
 import { getUserTheme } from "./getUserTheme";
+import { createRequire } from "module";
 
-// type WebpackPluginOption = {};
+declare const require: NodeRequire;
+declare const __ESM__: boolean;
+const _require = __ESM__ ? createRequire(import.meta.url) : require;
```
Comment (poteboy) [inline packages/webpack-plugin/src/plugin.ts:10]: @taishinaritomi 
The origin of the `__ESM__` variable are not immediately clear from this context alone. It would be helpful to include a comment explaining that this variable is declared in ``sup.config.ts ` and its intended use, for clarity to anyone reviewing or modifying this code in the future 🙏.

**Review by poteboy — APPROVED** [review]
LGTM, thanks! Just add the comment I mentioned earlier and everything is fine!

File: packages/webpack-plugin/package.json [hunk 2]
```diff
@@ -19,9 +19,29 @@
...
+      "import": "./dist/cssLoader.mjs"
+    },
+    "./assets/kuma.css": "./assets/kuma.css"
+  },
+  "typesVersions": {
+    "*": {
+      "registry": [
+        "./dist/registry.d.ts"
+      ]
+    }
```
Comment (kotarella1110) [inline packages/webpack-plugin/package.json:44]: I don't think `dist/registry.d.ts` exists, I think you can remove this.

File: packages/webpack-plugin/package.json [hunk 3]
```diff
@@ -19,9 +19,29 @@
...
+      "types": "./dist/loader.d.ts",
+      "require": "./dist/loader.js",
+      "import": "./dist/loader.mjs"
+    },
+    "./cssLoader": {
+      "types": "./dist/cssLoader.d.ts",
+      "require": "./dist/cssLoader.js",
+      "import": "./dist/cssLoader.mjs"
+    },
+    "./assets/kuma.css": "./assets/kuma.css"
```
Comment (kotarella1110) [inline packages/webpack-plugin/package.json:37]: The additional conditional exports are intended for internal implementation purposes only, so personally, I prefer not to disclose them casually. The reason is that making changes to these definitions in the future could result in disruptive modifications. I believe it would be better to either remove them or change the path in a way that conveys their internal use to the users.

```suggestion
    "./_internal/loader": {
      "types": "./dist/loader.d.ts",
      "require": "./dist/loader.js",
      "import": "./dist/loader.mjs"
    },
    "./_internal/cssLoader": {
      "types": "./dist/cssLoader.d.ts",
      "require": "./dist/cssLoader.js",
      "import": "./dist/cssLoader.mjs"
    },
    "./_internal/assets/kuma.css": "./assets/kuma.css"
```

File: packages/webpack-plugin/src/plugin.ts [hunk 4]
```diff
@@ -3,22 +3,19 @@ import { theme } from "@kuma-ui/sheet";
 import path from "path";
 import { readdirSync } from "fs";
 import { getUserTheme } from "./getUserTheme";
+import { createRequire } from "module";
 
-// type WebpackPluginOption = {};
+// tsup replaces this with `true` for esm build and `false` for cjs build.
```
Comment (poteboy) [inline packages/webpack-plugin/src/plugin.ts:8]:
```suggestion
// tsup will replace __ESM__ with true during ESM build and false during CJS build when bundling.
```

**Comment by poteboy** [comment]
It looks good to me. Can you check this PR again? @kotarella1110

**Review by kotarella1110 — APPROVED** [review]
LGTM🎉
